useTabs: false
tabWidth: 2
semi: false
printWidth: 100
singleQuote: true
trailingComma: none
svelteSortOrder: "options-scripts-markup-styles"
svelteStrictMode: false
svelteBracketNewLine: false
# svelteAllowShorthand: true
svelteIndentScriptAndStyle: true
